# .travis.yml
language: ruby
cache: bundler
before_install:
  - gem install bundler
  - gem install jekyll-algolia '~> 1.6'
script:
  - bundle exec jekyll algolia '~> 1.6'
branches:
  only:
    - master
rvm:
 - 2.4
