# .travis.yml
language: ruby
cache: bundler
before_install:
  - gem install bundler
  - gem install jekyll-algolia -v 0.0.0
script:
  - bundle exec jekyll algolia
branches:
  only:
    - master
rvm:
 - 2.4
